# Generated by Django 4.0.2 on 2022-02-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachersapplication', '0003_student_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.TextField(default='someone'),
        ),
    ]
